name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        if [ $RUNNER_OS == 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y cmake g++ libsfml-dev
        fi
        if [ $RUNNER_OS == 'Windows' ]; then
          choco install cmake
          choco install sfml
        fi

    - name: Set SFML_DIR environment variable
      run: |
        if [ $RUNNER_OS == 'Linux' ]; then
          echo "SFML_DIR=/usr/lib/cmake/SFML" >> $GITHUB_ENV
        fi
        if [ $RUNNER_OS == 'Windows' ]; then
          echo "SFML_DIR=C:/SFML/lib/cmake/SFML" >> $GITHUB_ENV
        fi

    - name: Set reusable strings
      id: strings
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DSFML_DIR=${{ env.SFML_DIR }} \
        -S ${{ github.workspace }}

    - name: Build the project
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test the project
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        if [ -f "CTestTestfile.cmake" ]; then
          ctest --build-config ${{ matrix.build_type }}
        fi
